#!/usr/bin/env python3
"""Builds pub/glass-icons.css: a SUBSET of the Lucide icon pack (ISC licence) as CSS masks.

Which icons: every name used as data-icon / data-icon-end in the demo, JS and CSS sources,
plus --g-i-<name> used by the kit itself, plus EXTRA. Source svgs: lucide-static (npm i lucide-static).
Use --all to emit the whole pack instead (about 2100 icons).
"""
import re, sys, os, glob

LUCIDE = os.environ.get('LUCIDE', '/tmp/lucide/node_modules/lucide-static/icons')
ROOT = os.environ.get('ROOT', '.')
SOURCES = [ROOT + '/demo.tpl.html', ROOT + '/pub/glass-ui.js', ROOT + '/pub/glass-ui.css']
EXTRA = ['info', 'check', 'triangle-alert', 'x', 'chevron-down', 'chevron-left', 'chevron-right', 'eye', 'eye-off', 'minus', 'plus', 'circle-help',
         # a small core of common UI icons, so the pack is useful beyond what the demo happens to use
         'arrow-left', 'arrow-right', 'arrow-up', 'arrow-down', 'chevron-up', 'menu', 'ellipsis', 'star', 'bookmark', 'external-link', 'filter', 'folder', 'image',
         'log-out', 'refresh-cw', 'send', 'sun', 'moon', 'circle-alert', 'circle-x', 'save', 'send', 'globe', 'camera', 'message-circle']

def used():
    names = set(EXTRA)
    for f in SOURCES:
        s = open(f).read()
        names |= set(re.findall(r'data-icon(?:-end)?=\\?"([a-z0-9-]+)\\?"', s))
        names |= set(re.findall(r'--g-i-([a-z0-9-]+)', s))
    names -= {'name', 'logo'}   # placeholders used in the docs
    return sorted(names)

def encode(svg_inner):
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' stroke-width='2' "
           "stroke-linecap='round' stroke-linejoin='round'>" + svg_inner + "</svg>")
    svg = svg.replace('"', "'")
    return 'url("data:image/svg+xml,' + svg.replace('%', '%25').replace('<', '%3C').replace('>', '%3E').replace('#', '%23') + '")'

def inner(path):
    s = open(path).read()
    s = re.sub(r'<!--.*?-->', '', s, flags=re.S)
    m = re.search(r'<svg[^>]*>(.*)</svg>', s, re.S)
    body = re.sub(r'\s+', ' ', m.group(1)).strip()
    return re.sub(r'\s*/>', '/>', re.sub(r'>\s+<', '><', body))

def build(names):
    out = ['''/*!
 * Glass UI icons: a subset of Lucide (https://lucide.dev, ISC licence, (c) Lucide Contributors; Feather portions (c) Cole Bemis), as CSS masks.
 * Generated by build_icons.py from the names used in the kit and the demo. Do not edit by hand.
 *
 *   <button data-icon="play">Play</button>   <button data-icon="heart" aria-label="Favourite"></button>   <span data-icon="check"></span>
 *
 * Add your own icon (a 24x24 single-colour svg, stroke or fill):
 *   :root { --g-i-logo: url("data:image/svg+xml,...") }
 *   [data-icon="logo"] { --g-is: var(--g-i-logo) }   [data-icon-end="logo"] { --g-ie: var(--g-i-logo) }
 */
:root {''']
    missing = []
    body = []
    for n in names:
        p = os.path.join(LUCIDE, n + '.svg')
        if not os.path.exists(p):
            missing.append(n); continue
        out.append('  --g-i-%s: %s;' % (n, encode(inner(p))))
        body.append('[data-icon="%s"] { --g-is: var(--g-i-%s); }\n[data-icon-end="%s"] { --g-ie: var(--g-i-%s); }' % (n, n, n, n))
    out.append('}')
    out.extend(body)
    return '\n'.join(out) + '\n', missing

if __name__ == '__main__':
    names = sorted(os.path.basename(f)[:-4] for f in glob.glob(LUCIDE + '/*.svg')) if '--all' in sys.argv else used()
    css, missing = build(names)
    open(ROOT + '/pub/glass-icons.css', 'w').write(css)
    print(len(names) - len(missing), 'icons,', len(css), 'bytes')
    if missing: print('MISSING in Lucide:', ', '.join(missing))
